import Head from "next/head";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

export default function Home({ newsResult, randomUsers }) {
    return (
        <div className="">
            <Head>
                <title>Twitter Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex min-h-screen max-w-7xl mx-auto ">
                {/*  Sidebar */}
                <Sidebar></Sidebar>

                {/*  Feed */}
                <Feed></Feed>

                {/*  Widgets */}
                <Widgets
                    newsResult={newsResult.articles}
                    randomUsers={randomUsers.results}
                />
                {/*  Modal */}
            </main>
        </div>
    );
}
//https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
export async function getServerSideProps() {
    const newsResult = await fetch(
        "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
    ).then((res) => res.json());

    const randomUsers = await fetch(
        "https://randomuser.me/api/?results=30&inc=name,login,picture"
    ).then((res) => res.json());
    return {
        props: {
            newsResult,
            randomUsers,
        },
    };
}
